### ISSUE TITLE
feature request: reload without reset

### ISSUE THREAD

**Issue by CharlesGueunet** [ilyachur/cmake4vim#1]
Hello,
Thank you for this awesome plugin, very useful :)
Would it be possible to have a reload feature to set the `g:cmake_build_type` to the current cached value inside the CMake ? I often change between Release and Debug and that would help me avoid some accidental full rebuild when I mistakenly rebuild my Debug folder using the Release flag.

Thanks again for this work,
Charles

**Comment by ilyachur** [comment]
Hello Charles,

Thanks for your feedback!

Do you change `g:cmake_build_dir` in order to change between Release and Debug?
As a WA you can use **CMakeSelectTarget** command in order to select the target and build configuration from the cache.

**Comment by CharlesGueunet** [comment]
Thank you for your quick answer,
for now I am using these two commands:
* `command! CMakeDebug let g:cmake_build_type="Debug" | let g:cmake_build_target="install" | CMake`
* `command! CMakeRelease let g:cmake_build_type="Release" | let g:cmake_build_target="install" | CMake`
And I need to call theme whenever I change my *build/* directory to be the Release or the Debug one.
What I would like is a command that set the `g:cmake_build_type` accordingly to the *CMakeCache* (I think this plugin did that some times ago).
The `:CMakeSelectTarget install` select the good target but set the the build type to Release in my experience, even if my *CMakeCache* contains Debug mode.

Charles

**Comment by ilyachur** [comment]
Ok, 

Hmm, I thought that CMakeSelectTarget doesn't depends on build type.

I understood your request.
In the last commit I added this feature. Currently plugin will try to get build type from CMake cache if you haven't cmake_build_type variable.
Could you check it?

**Comment by CharlesGueunet** [comment]
It works like a charm :)
Thank you for the feature and for your reactivity !

Charles
