### ISSUE TITLE
CMakeRun output with job executor can have several empty lines

### ISSUE THREAD

**Issue by ilyachur** [ilyachur/cmake4vim#103]
**Describe the bug**
I found that `:CMakeRun` output can  contain different number of empty lines:
```
      - Expected:
          || --gtest_filter=Test* F1
      - Got:
          ||
          || --gtest_filter=Test* F1
          ||
          ||
          ||
```

**To Reproduce**
1. In PR https://github.com/ilyachur/cmake4vim/pull/101 I added a new test, but cannot compare output because it is different for different platforms
2. Need to enable the test and fix the issue

**Comment by mark2185** [comment]
@ilyachur was this with `vim` or `neovim`?

**Comment by ilyachur** [comment]
I found the issue in CI history and it is reproduced only on `neovim`.
