### ISSUE TITLE
How to choose which cmake to use?

### ISSUE THREAD

**Issue by xubury** [ilyachur/cmake4vim#111]
For example, I would like to use mingw-cmake for my project, how can I do that?

**Comment by ilyachur** [comment]
Hi @xubury,

At the current moment the plugin uses the default cmake command. You can redefine default cmake in your environment.

But in general, I can add an option to plugin which will allow to specify cmake executable.

**Comment by xubury** [comment]
I though about soft linking cmake to mingw-cmake. But I am worried that may break other project that don't use mingw toolchain.

**Comment by ilyachur** [comment]
Yeah, I got.

Can you develop these projects in different environment?

I will try to prepare PR on a weekends with CMake executor customisation.

**Comment by mark2185** [comment]
@xubury until such a feature is implemented, you can just change the name of `cmake` in [this](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/cmake.vim#L258) line.

E.g.
```
    let l:cmake_cmd = 'mingw-cmake ' . join(l:cmake_args) . ' ' . join(a:000)
```

**Comment by ilyachur** [comment]
Created PR https://github.com/ilyachur/cmake4vim/pull/112 with `g:cmake_executable` option

**Comment by ilyachur** [comment]
@xubury PR was merged to the master branch. Please verify that it works for your cases. Thanks!

**Comment by xubury** [comment]
@ilyachur yes, it works perfectly! Thanks a lot!
