### ISSUE TITLE
Scrolling buffer in output

### ISSUE THREAD

**Issue by Midren** [ilyachur/cmake4vim#114]
**Is your feature request related to a problem? Please describe.**
If I am running using `CMakeRun` I am constantly pressing `G` to get the latest output, as it mainly interests me.

**Describe the solution you'd like**
I think, that behavior can similar to Vimspector. If the last cursor position was one the last line, the buffer will be automatically scrolled. Otherwise, it will remain in the same position.

**Comment by mark2185** [comment]
Please provide additional info as stated in the issue template:
```**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS]
 - Editor [e.g. vim, nvim]
 - Version [e.g. 8.1]

**Additional context**
Add any other context about the problem here.
```
Could you clarify which buffer is in question and which executor? And if it's `nvim` or `vim` since I'm pretty certain `nvim` implementation is the shabbier one.
I'm asking because when using `'job'` executor the `cmake4vim_execute` (the buffer when you run `:CMakeRun`) is following the output.

**Comment by Midren** [comment]
I was using `job` executor and didn't know that such behavior was intended, so I used the template for the feature requests.

**To Reproduce**
Steps to reproduce the behavior:
1. Run `CMakeRun`
2. Switch to `cmake4vim_execute` buffer
3. Scroll down to the last line
4. As the program is running, new lines are added, and cursor is not on the last line

**Expected behavior**
Buffer will be automatically scrolling when new lines are added

**Desktop (please complete the following information):**
 - OS: macOS
 - Editor: nvim
 - Version: NVIM v0.5.0-dev

**Comment by mark2185** [comment]
Ah yes, that's what I thought, `neovim`. I'll push a fix in the morning.

**Comment by Midren** [comment]
@mark2185 I can confirm that it helps always to scroll as new data arrives. However, I think that Vimspector has a more convenient approach:
1. It scrolls the output not only when the cursor is the buffer with output (`cmake4vim_execute` in this case)
2. It stops scrolling if you try to move cursor from the last line

**Comment by mark2185** [comment]
> @mark2185 I can confirm that it helps always to scroll as new data arrives. However, I think that Vimspector has a more convenient approach:
> 
> 1. It scrolls the output not only when the cursor is in the buffer with output (`cmake4vim_execute` in this case)
> 2. It stops scrolling if you try to move cursor from the last line

Which of the `Vimspector` buffers would that be?

**Comment by Midren** [comment]
@mark2185 In my case, it is `codelldb`.

**Comment by mark2185** [comment]
> @mark2185 In my case, it is `codelldb`.

@Midren that window is actually a `terminal` and that's the default behaviour of the terminal (regardless whether it's _in_ vim or not), so there's not much we can do about that since `Vimspector` doesn't do anything special with it either. Sorry.

**Comment by Midren** [comment]
@mark2185 I see, I think because of it, colors are also preserved in `Vimspector`

**Comment by mark2185** [comment]
@Midren that's right. `cmake4vim_execute` is an ordinary buffer so it doesn't parse ANSI color codes.

**Comment by Midren** [comment]
@mark2185 Are any reasons, why it is an ordinary buffer, or `terminal` could be used instead?

**Comment by mark2185** [comment]
@Midren well no particular reason, I guess, @ilyachur might know more since he's the one who wrote the first version. 

It's elegant, making `job` output to a `buffer` is just an option of `job_start`. 
I guess we _could_ add an option to have `async` jobs run in a split `terminal` as well, but that would require `neovim/vim` specific code, additional flags, and I'm not sure if it's worth it. I'll discuss it with Ilya and we'll see!

Btw, have you tried `let g:cmake_build_executor='dispatch'`? That sort of does what you're describing.

**Comment by ilyachur** [comment]
@mark2185 @Midren I think we can add the `terminal` support, it can be the new executor. But in general no particular reason 😄 The initial plugin version had support only `Dispatch`.

I think Luka is right and `Dispatch` can help you, it can use the separate terminal for tasks.

**Comment by ilyachur** [comment]
@Midren Did the fix solve your issue?

**Comment by Midren** [comment]
@ilyachur Dispatch with output in tmux is definitely a way to go now. However, without tmux a quickfix is always changing and my cursor is jumping to it. It would be cool to have `terminal` support to be able work without tmux, but for now it is okay ) 

Thanks !
