### ISSUE TITLE
Pass custom flags to make command

### ISSUE THREAD

**Issue by HugoPeters1024** [ilyachur/cmake4vim#139]
(I know the readme mentions this exact example but I can't seem to find the option)

**Is your feature request related to a problem? Please describe.**
I can't seem to build in parallel using e.g. `-j12`, slowing down my development experience

**Describe the solution you'd like**
The ability to pass args to the make step

**Describe alternatives you've considered**
I don't think you can pass this arg to cmake and bake it in the Makefile

**Comment by HugoPeters1024** [comment]
Wow not sure how I missed that, thanks for helping out an ignoranus like me :P

**Comment by mark2185** [comment]
@HugoPeters1024 I'm too lazy for gmail so - if you haven't tried it out already, check out `ninja`, it is faster than `make` for incremental builds and it's parallel by default.
