### ISSUE TITLE
Specify cwd when invoking `:CMakeRun`

### ISSUE THREAD

**Issue by sam20908** [ilyachur/cmake4vim#143]
**Is your feature request related to a problem? Please describe.**
Currently, there's no (or not documented) method to change the cwd when running `:CMakeRun`

**Describe the solution you'd like**
Perhaps a use variable the user can set, like `cmake_run_cwd`?

**Describe alternatives you've considered**

**Additional context**

**Comment by ilyachur** [comment]
@sam20908 

`:CMakeRun` command executes the binary from the current executable target.
It means if you want to change the executable file, you need to change the CMake target.

But `:CMakeRun` allows to specify command line arguments for the executable. You can just add these arguments to command line:
`:CMakeRun arg1 arg2 arg3`

**Comment by sam20908** [comment]
What I'm asking is how to change the _current working directory_ when I run the executable.

**Comment by ilyachur** [comment]
Yes, sorry, my mistake.
In general, at the current moment, CMakeRun doesn't change CWD.
You can try to change work directory before CMakeRun command

**Comment by mark2185** [comment]
You could always open up a terminal in a new tab/split and just re-run the binary there every time you need to.

Or even add a mapping that does that for you.

**Comment by ilyachur** [comment]
Yes, for future, I think vimspector config could be used to specify work directory.
But currently it is not supported

**Comment by mark2185** [comment]
It [does support it](https://github.com/puremourning/vimspector#c-c-rust-etc), the key is `cwd`. It has to be modified manually, though.

**Comment by ilyachur** [comment]
> It [does support it](https://github.com/puremourning/vimspector#c-c-rust-etc), the key is `cwd`. It has to be modified manually, though.

Vimspector support CWD and Vimspector config contains this key, but `:CMakeRun` command doesn't read this key from the Vimspector config.
