### ISSUE TITLE
system call in createLink may cause problem

### ISSUE THREAD

**Issue by xubury** [ilyachur/cmake4vim#144]
In the following snippet, the `system()` call differs based on the os.
However, it is possible to use `bash` as shell in windows (mingw program) where `copy` is not a valid command.
So, perhaps it's better to change `has('win32')` to something like `&shell =~# 'cmd\.exe' || &shell =~# 'powershell\.exe'`?
https://github.com/ilyachur/cmake4vim/blob/7947f033dc9bf5fc1c9255c25979afb5ae30cb1f/autoload/utils/fs.vim#L43-L54

**Comment by mark2185** [comment]
Could you test this out?

```diff
- if has('win32')
+ if has('win32') && !has('win32unix')
```

**Comment by xubury** [comment]
Just tested it, `has('win32') && !has('win32unix')` return 1 on my neovim, 
but on the vim provided by mingw64 it return 0.
I think it's beacause my neovim is the win64 version, so the `win32unix` flag is not set during compilation?

**Comment by mark2185** [comment]
`neovim` in general doesn't support the `win32unix` feature flag - [related issue](https://github.com/cascent/neovim-cygwin/issues/5).

Yeah, I'm not sure how to proceed with this, let's wait for @ilyachur.

**Comment by ilyachur** [comment]
Hi @xubury thank you for the issue.

I think the issue can be solved be next code:
```
if executable('copy')
    silent call system('copy ' . utils#fs#fnameescape(a:src) . ' ' . utils#fs#fnameescape(a:dst))
elseif executable('ln')
    silent call system('ln -s ' . utils#fs#fnameescape(a:src) . ' ' . utils#fs#fnameescape(a:dst))
else
    call utils#common#Warning('Cannot create link!')
else

**Comment by mark2185** [comment]
@xubury can you give it a spin and let us know if it works for you?

**Comment by xubury** [comment]
@mark2185 sorry for the delay, just tested the code above and it works for me!
