### ISSUE TITLE
`:CMakeBuild` command ignores the build folder created by `:CMake` with overridden `cmake_build_dir`

### ISSUE THREAD

**Issue by AlexVdberg** [ilyachur/cmake4vim#155]
**Describe the bug**
`:CMakeBuild` command ignores the build folder created by `CMake` with overridden `g:cmake_build_dir`. It appears to not pick up the new directory's name the first time `:CMake` is run and will build the default build folder (`cmake-build-Release`) files instead. This only occurs if there is no build folder when vim is started or if the build folder is deleted by `CMakeReset`

I have found 2 workarounds to this error. The easiest is to run `CMake` twice before running `CMakeBuild`. The second method is to generate the build folder before opening vim (or generate in vim, exit and re-open).

Obviously this isn't really a problem when you're continuing development on something, but as someone looking to use this plugin for the first time on a new project, I almost went to a different plugin. At the very least, the bug is documented now.

**To Reproduce**
1. Go to a cmake project
2. Delete the `build` or `cmake-build-Release` folder
3. Set `let g:cmake_build_dir = "build"` in `.vimrc`
4. open vim in the project
5. run `:CMake` (Creates `build` folder)
6. run `:CMakeBuild` 
Fails with the following error:
```
Error detected while processing function cmake4vim#CMakeBuild[1]..utils#cmake#findBuildDir[6]..utils#cmake#common#getInfo[6]..utils#cmake#common#collectCMakeInfo[1]..utils#cmake#fileapi#parseReply[6]..<SNR>50_parseAll:
line    1:
E484: Can't open file <empty>
```

The error can also be reproduced with:
1. Go to a cmake project directory
2. generate build folder: `cmake -S . -B build`
3. Set `let g:cmake_build_dir = "build"` in `.vimrc`
4. open vim
5. run `:CMakeBuild` (builds fine)
6. run `CMakeReset`
7. run `CMake`
8. run `CMakeBuild` (fails with same error as above)

**Expected behavior**
The desired effect is that the project will build in the `cmake_build_dir` folder

**Screenshots**
This is what shows after step 6 of the first instructions. Its 8 in the second instructions.
![image](https://user-images.githubusercontent.com/22566677/166130941-2b7b2308-f628-4622-b263-bbd70165338f.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 21.2.2
 - Editor gvim
 - Version 8.2

**Additional context**
I'm running vim in tmux and alacritty. I just checked now, and using Manjaro's default `Xfce Terminal` without tmux still has the error.

**Comment by ilyachur** [comment]
Hi @AlexVdberg,

Thanks for the detailed description. I will take a look.

**Comment by ilyachur** [comment]
Hi @AlexVdberg,

I won't be able to reproduce the issue on macOS with the same environment (tmux, alacrity and vim).
I created a fix which should allow to avoid your issue. Could you verify PR #156 before the merge? I want to be sure that it solves your original issue.

**Comment by AlexVdberg** [comment]
I gave it a try and it works in my environment (both alacritty+tmux+vim, and Xfce Terminal+vim)
That was fast! Awesome! Thanks!

**Comment by ilyachur** [comment]
Ok, I will merge PR.
