### ISSUE TITLE
Documentation jump to errors/warnings

### ISSUE THREAD

**Issue by chreg** [ilyachur/cmake4vim#16]
Hello there, 

could you extend the documentaiton on how to jump to errors/warnings, which keys/commands i should use. I am quite new to vim. 

Thank you in advance!

**Comment by ilyachur** [comment]
Hi @chreg,

Thank you for the issue!
At the current moment I didn't implement jump to error functionality. At the current moment I use vim search in order to find CMake errors or warnings.

I will think about this improvements.

Thank you.

**Comment by ilyachur** [comment]
Hi @chreg,

This plugins handles cmake error messages and you can use quickfix list features to jump to next/previous error/warning messages
```
:cn[ext].          #Jump to next error
:cp[revious]   # Jump to previous error
```

**Comment by chreg** [comment]
Hi @ilyachur 

thank you for the response and the update. I will test this next week and tell the results afterwards.

Best Regards 
chreg

**Comment by ilyachur** [comment]
Hi @chreg,

Did you have a chance to check the solution for the issue?

**Comment by ilyachur** [comment]
@chreg I will close the ticket because I didn't get a response for a long time.
Feel free to reopen it if you have any questions.
