### ISSUE TITLE
CMakeBuild command produces error message  ' Key not present in Dictionary: "client-cmake4vim" '

### ISSUE THREAD

**Issue by csy19960309** [ilyachur/cmake4vim#163]
**Describe the bug**
As what is described in the title.

**To Reproduce**
1. Generate build files with VSCode to the directory 'build'.
2. Set ' let g:cmake_build_dir =  "build" ' at the './nvimrc'.
3. Run command CMakeBuild in Neovim.

**Expected behavior**
Building process runs.

**Screenshots**
![屏幕截图(15)](https://user-images.githubusercontent.com/12546423/192089817-566831ec-46b9-43f1-9d9a-ae072ce5027f.png)

**Desktop (please complete the following information):**
 - Windows
 - nvim
 - v0.7.2

**Additional context**
None.

**Comment by mark2185** [comment]
Could you try setting the absolute path? I tried it with a relative path, but still.

Could you also try `vim` instead of `neovim`?

**Comment by mark2185** [comment]
Based on a bit of googling, the correct location for `nvimrc` is `~/.config/nvim/init.vim` - here's [an issue](https://github.com/neovim/neovim/issues/3530) about that. Try checking that.

**Comment by csy19960309** [comment]
> Based on a bit of googling, the correct location for `nvimrc` is `~/.config/nvim/init.vim` - here's [an issue](https://github.com/neovim/neovim/issues/3530) about that. Try checking that.

I am sure the '.nvimrc' is working . This is not where the issue remains.
I'll check if the issue is also there in Vim at some time.
Thanks for immediate reply.

**Comment by mark2185** [comment]
Try setting the absolute path before trying out `vim`. 

Also print out the variable before running `CMakeBuild`.

**Comment by csy19960309** [comment]
> Try setting the absolute path before trying out `vim`.
> 
> Also print out the variable before running `CMakeBuild`.

You are right, setting the absolute path solved the problem because '.nvimrc' is invoked at init.lua so relative path points to a directory based on where the init.lua locates. Thanks for your help.
