### ISSUE TITLE
Cursor goes to EOF when building or running

### ISSUE THREAD

**Issue by rav-en** [ilyachur/cmake4vim#189]
**Describe the bug**
Cursor goes to the end of the file when CMakeBuild or CMakeRun

**To Reproduce**
CMakeBuild or CMakeRun a file with a few lines to test behavior. 

**Expected behavior**
Cursor to stay on current line that was edited at the time of CMakeBuild or CMakeRun

**Screenshots**
no screenshots.

**Desktop :**
os : Debian 5.10.179-1 (2023-05-12)
nvim: v0.9.0
cmake4vim: 3.18.4

**Comment by ilyachur** [comment]
Hi @rav-en ,

It looks strange, I never saw such behaviour on my configuration. Could you please provide mode information? What executor (term, jobs, dispatch) do you use?
Also could you try to disable other plugins to be sure that `cmake4vim` causes this behaviour?

**Comment by rav-en** [comment]
Forgive my ignorance,  How do I find the executor (term, jobs, dispatch) information?

**Comment by ilyachur** [comment]
The [README](https://github.com/ilyachur/cmake4vim#common) provides this information:
<img width="808" alt="Screenshot 2023-06-07 at 07 30 43" src="https://github.com/ilyachur/cmake4vim/assets/4737252/30d2bb1c-33e7-42d2-82aa-66fc82b83b45">
If you don't specify, it uses first available executor in this order: dispatch, job, term, system

**Comment by i-ilak** [comment]
I know the issue has been closed, but maybe for anybody who stumbles across this and to make it explicit: If you don't have `vim-dispatch` installed and don't change the `g: cmake_build_executor` option to something else then the default, it will behave as explained in the bug report.

Installing `vim-dispatch` or switching it to `job` worked for me to fix it.

**Comment by i-ilak** [comment]
@ilyachur Is there any specific reason why this behavior happens only with the `job` mode?
