### ISSUE TITLE
Possiblity to change `cmake_build_executor` split to vertical split

### ISSUE THREAD

**Issue by i-ilak** [ilyachur/cmake4vim#196]
**Is your feature request related to a problem? Please describe.**
I work on a wide, but not very high screen and would like to see the build log not in a horizontal, but vertical split.

**Describe the solution you'd like**
Currently, there is a setting to change the `mode`, i.e. `job, dispatch, etc.` and `g:cmake_build_executor_height` to set the height of the executor split.

Would be nice to have three variables:
* the one to set the mode stays the same,
* `g:cmake_build_executor_split_type` is 'horizontal' or 'vertical' (default can stay 'horizontal'),
* `g:cmake_build_executor_size` to set size (default can stay `10`)

**Describe alternatives you've considered**
Not sure if there are alternatives, or if this can already be achieved (I at least didnt find anything in the `README`).

**Comment by ilyachur** [comment]
Hi @i-ilak, 

I created PR #197.
Hope, it should help you.

**Comment by ilyachur** [comment]
@i-ilak PR was merged. Feel free to reopen the issue in case if you have any problems.

**Comment by i-ilak** [comment]
@ilyachur Thanks a lot for the quick action! 

The PR seems not to work for me. I updated this morning to master (and checked the log to make sure your changes are there), but after setting the two new variables 
```lua
vim.g.cmake_build_executor_window_size = 25
vim.g.cmake_build_executor_split_mode = 'vsp'
```
and restarting `nvim`, the split is still horizontal and the window size is the default of `10`. The other variables `vim.g.cmake_build_path_pattern, vim.g.cmake_variants, etc` are picked up correctly and work as expected. Any ideas what is going on?

**Comment by ilyachur** [comment]
Hmm, I tested on `vim` and `nvim`... And it worked for me...
Could you please provide information about plugin configuration? Build executor and etc.?

**Comment by i-ilak** [comment]
@ilyachur My issue seems to be related to `vim-dispatch`. After adding 
```lua
vim.g.cmake_build_executor = "job"
```
the feature works as expected... Sorry for the troubles!

**Comment by ilyachur** [comment]
@i-ilak Oh, good, thank you for sharing.

Unfortunately yes, my changes didn't affect dispatch, it works only for others executors.
I don't know the simple way how to support vertical layout with dispatch... Sorry :(

**Comment by i-ilak** [comment]
@ilyachur No problem of course. Thanks a lot for the help. Will close the issue  :raised_hands:
