### ISSUE TITLE
License isn't specified.

### ISSUE THREAD

**Issue by LGlowczyk** [ilyachur/cmake4vim#2]
Hi

cmake4vim looks like a nice plugin but it doesn't have license explicitly set. This may block some potential users. 

Can you add license to this project?

BR
Łukasz

**Comment by ilyachur** [comment]
Hi Łukasz,

I added GPL-3 licence to this project.
I hope it will be convenient for all potential users.

--
Ilya

**Comment by LGlowczyk** [comment]
Thanks.

**Comment by ilyachur** [comment]
License was changed to MIT.
