### ISSUE TITLE
Unit test should run on pull request

### ISSUE THREAD

**Issue by salco** [ilyachur/cmake4vim#29]
I think it can help the pull request to get feedback on unit test from github-action.

In [.github/workflows/linux.yml](https://github.com/ilyachur/cmake4vim/blob/master/.github/workflows/linux.yml#L3) and [.github/workflows/windows.yml](https://github.com/ilyachur/cmake4vim/blob/master/.github/workflows/windows.yml#L3)

To do that, we could add `pull_request` .

**Comment by ilyachur** [comment]
Created a PR: https://github.com/ilyachur/cmake4vim/pull/30

**Comment by ilyachur** [comment]
I merged PR to the master branch
