### ISSUE TITLE
Extra quotes in build path when using :CMakeBuild

### ISSUE THREAD

**Issue by sam20908** [ilyachur/cmake4vim#32]
**Describe the bug**
When I try doing `:CMakeBuild`, it puts extra quotes around the build folder name, hence making the build fail.

**To Reproduce**
1. Find any CMake project
2. Do `:CMake` (it succeeds for me)
3. Do `:CMakeBuild`

**Expected behavior**
The build should succeed

**Screenshots**
![f783df6cb6ff2cbf2e28fdee15071c3e](https://user-images.githubusercontent.com/18388795/95797863-6810ca00-0ca5-11eb-9f99-874bc6a96c0c.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Neovim
 - v0.4.4

**Additional context**

**Comment by ilyachur** [comment]
Hi @sam20908 ,

Could you provide details? Do you change any options of the plugin or use all options with default values?
I didn't faced with such issue. Maybe it is a nvim or windows related issue. I need to investigate it.

**Comment by sam20908** [comment]
Yes, I didn't change anything in the plugin (all using default options).

**Comment by sam20908** [comment]
Okay, so I found out that it's a Windows issue. Windows doesn't allow quotes in folder or file names in path.

**Comment by ilyachur** [comment]
But I tried to reproduce the issue with vim on Windows and all was good. (Moreover I have a validation step to check that plugin works on  Windows and CI works well).
I will try maybe it is a combination Windows + nVim.
Also plugin doesn't add any single quotes to the build path.

**Comment by sam20908** [comment]
Hmm... I'll try it with Vim and Neovim to see which one doesn't work.

**Comment by sam20908** [comment]
It is indeed a Neovim issue.

**Comment by ilyachur** [comment]
Will have a look how we can avoid this issue

**Comment by ilyachur** [comment]
@sam20908 I switched vim to neovim in the PR https://github.com/ilyachur/cmake4vim/pull/40 but windows CI is [passed](https://github.com/ilyachur/cmake4vim/pull/40/checks?check_run_id=1336700741).
Could you check that issue is still reproduced?

**Comment by sam20908** [comment]
The issue still happens.

**Comment by ilyachur** [comment]
@sam20908 If issue is still happened, may I ask you to try next things:
- What CMake generator do you use? (You can use CMakeInfo command in order to get detailed information)
- Could you try to reproduce the issue on clean neovim (without plugins and your configurations)?

**Comment by sam20908** [comment]
Output from `:CMakeInfo`:
![image](https://user-images.githubusercontent.com/18388795/97805247-c75d5c80-1c09-11eb-98e6-a338c3caa683.png)

Same output with just your plugin and no personal configuration:
![image](https://user-images.githubusercontent.com/18388795/97805300-14413300-1c0a-11eb-9fbb-96ef495fbfac.png)
I also found out that this also affects the command `:CMakeClean`, where it tries to get the build directory.

**Comment by ilyachur** [comment]
Hmmm, it is strange that CMAKE_GENERATOR is also empty... Maybe it is the same issue with build folder path.

I created a draft PR https://github.com/ilyachur/cmake4vim/pull/41, where I removed `shellescape` command. Could you please try to use this PR? Maybe it can help to solve the issue.

**Comment by sam20908** [comment]
Thanks! But how will I get the PR through Vundle (the package manager I'm using)? Is there some special command?

**Comment by ilyachur** [comment]
@sam20908 Hmmm, I didn't use Vundle... As I understood it doesn't have a mechanism to specify branch.
Could you manually checkout the branch and check the issue?

**Comment by sam20908** [comment]
@ilyachur It fixes it! 🥳 

But I encountered a separate issue relating to having space in the project path (no space works fine). Should I open a separate issue for that?

**Comment by ilyachur** [comment]
@sam20908 In the PR https://github.com/ilyachur/cmake4vim/pull/45 I tried to fix your original problem and also fixed the problem with spaces in the path. This PR already was merged to master.
Could you check that it works for your cases?

**Comment by sam20908** [comment]
@ilyachur It works now as well! 🥳 

Although it works, it still displays a warning message about not being able to create the build directory, but the command succeeds anyway.
![image](https://user-images.githubusercontent.com/18388795/98122184-15ba6780-1e65-11eb-8cd7-9e70f569f849.png)

This message displays with commands `:CMake` and `:CMakeBuild`.

**Comment by ilyachur** [comment]
Ok, cool, I am happy to hear that it works.

But I didn't understand how you get the "Cannot create a build directory" error message. Maybe something with access rights, because I cannot emulate this behaviour and cannot cover this line in tests 😄

**Comment by sam20908** [comment]
Yeah, I find that weird as well. Should I close this issue now?

**Comment by ilyachur** [comment]
If it works for you, yes, I think we can close the ticket.

**Comment by sam20908** [comment]
Alright. I can ignore the warning message since it doesn't bother me that much. 👍

**Comment by ilyachur** [comment]
@sam20908 If you understand why you get this error message, please share this information with me.
Because I cannot reproduce this behaviour. Moreover, I added Neovim to CI and in CI I also don't see such problems.

**Comment by sam20908** [comment]
@ilyachur Yeah I also don't understand either :| .
