### ISSUE TITLE
Verbose during build and generation

### ISSUE THREAD

**Issue by alexandreSalconiDenis** [ilyachur/cmake4vim#33]
**Is your feature request related to a problem? Please describe.**
In my usage of cmake, when I call `cmake` to generate everything it can take 2-5 minute depending if im on windows or linux (due to the `fetchcontent` I think).

And the build can also take 1-2 min if it's the end of my project.

So I think it can be a nice feature to output in a sideview the build and let the user continue to work during that.

**Describe the solution you'd like**
I've made a path on top of the commit `f62046f` but the project really change since that but the idea could still work: using `job_start` to build in background the stuff and use buffer in a sideview to show cmake.

**Additional context**
I will rework what I did with the new layout and propose something if you like.

**Comment by ilyachur** [comment]
Hi @alexandreSalconiDenis,

I use [vim-dispatch](https://github.com/tpope/vim-dispatch) plugin for such things.
I created a [special methods](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/common.vim#L4) which allow to use different approaches to call commands.
Do you want to modify `utils#common#runSystem(cmd)` command or create something new?

**Comment by alexandreSalconiDenis** [comment]
okok, I was wondering why this setup was split. if it's the case I thnik the only part need to change would be [runSystem](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/common.vim#L15).

**Comment by ilyachur** [comment]
@alexandreSalconiDenis I created a PR https://github.com/ilyachur/cmake4vim/pull/64 where I have added support of async run without plugins

**Comment by ilyachur** [comment]
@alexandreSalconiDenis PR was merged to the master branch. Please verify that it works for your cases.

**Comment by alexandreSalconiDenis** [comment]
With that I can work on my file during the compilation.
The only thing is that It doesn't seam's to report error correctly. 
With `g:cmake_build_executor= system` I get all compilation error but with `g:cmake_build_executor= job` it look like a partial output.
Not sure if it's part of this issue, if not we can discuss about it in another issue and close this one?
Because the job open a buffer and close itself correctly .

**Comment by ilyachur** [comment]
@alexandreSalconiDenis Hmm, looks strange.
I haven't got a partial output when I tested this feature.

Could you provide a reproducer (maybe you can use `test proj` to reproduce)? I propose to create a new issue for this problem.
