### ISSUE TITLE
[SUGGESTION] :CMakeRun / :CMakeDebug

### ISSUE THREAD

**Issue by silvioprog** [ilyachur/cmake4vim#6]
Hello.

Firstly, thanks for this incredible VIM plugin! I'm enjoying it a lot in nvim with LSP provided by Coc plugin. :-)

So, I have a suggestion for cmake4vim. It would be nice the following options:

`:CMakeRun` - runs the program selected by `:CMakeSelectTarget`. It compiles the program automatically if it is not compiled yet.
`:CMakeDebug` - it is similar to `:CMakeRun`, but allowing to debug the program.

Maybe the `:packadd termdebug/:Termdebug` and `:Run` could help to implement the suggested options: https://www.dannyadam.com/blog/2019/05/debugging-in-vim/.

**Edit1:**

It seems [vimspector](https://github.com/puremourning/vimspector) is a promising [DAP](https://microsoft.github.io/debug-adapter-protocol) plugin, maybe it could be used instead of `:termdebug`.

More info [about the plugin (features, shortcuts etc.)](https://puremourning.github.io/vimspector-web/) and [how to debug C applications using it](https://puremourning.github.io/vimspector-web/demo-setup.html).

**Edit2:**

In attachment a short video showing the vimspector debugging a small HTTP server in C.

Thank you!

![dap](https://user-images.githubusercontent.com/1456829/64194864-811a3b00-ce56-11e9-8748-1675abe2c85a.gif)

**Comment by Shatur95** [comment]
Why this issue was closed?

**Comment by ilyachur** [comment]
Hmm I hope PR https://github.com/ilyachur/cmake4vim/pull/76 should add the opportunity to debug targets using the Vimspector

**Comment by ilyachur** [comment]
PR was merged. I hope the plugin should allow to run and debug your applications.
