### ISSUE TITLE
CTest unknown target

### ISSUE THREAD

**Issue by mark2185** [ilyachur/cmake4vim#67]
**Describe the bug**
When running `CTest` with the `ninja` generator the testing fails with
```
|| ninja: Entering directory `/Users/mark/workspace/build/project/clang/Release'
|| ninja: error: unknown target 'ARGS='
```
Actual command that was run:
`:Dispatch cmake --build /Users/mark/workspace/build/project/clang/Release --target test -- -C /Users/mark/workspace/build/project/clang/Release ARGS=""`

**To Reproduce**
1. Run `:CMake` and `:CMakeBuild`
2. Run `:CTest`
3. See error

**Expected behavior**
I would expect that it behaves the same as running `ctest` in the build directory.

**Desktop:**
 - OS: macOS
 - Editor: terminal vim ( installed `macvim` through `brew` )
 - Version: 8.2

**Comment by ilyachur** [comment]
Created a PR https://github.com/ilyachur/cmake4vim/pull/70 which should solve the issue.

**Comment by ilyachur** [comment]
@mark2185 PR was merged. Please verify the latest master.

**Comment by mark2185** [comment]
Works great, thanks!
