### ISSUE TITLE
E706: Variable type mismatch for: l:version_str in utils#cmake#getVersion()

### ISSUE THREAD

**Issue by WojciechMula** [ilyachur/cmake4vim#77]
First of all, thank you for this great package!

I started to use it on my local machine, and decided to install it also on a work machine. Unfortunately, I got this error on VIM from RedHat (version: `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 22 2018 06:34:52)`)

The following local fix helped (introduced a new variable for `split` result). I'm completely unfamiliar with VIM script, so don't know it's a real fix or just workaround.

```
" Gets CMake version
" Returns array [major, minor, patch]
function! utils#cmake#getVersion() abort
    let l:version_out = system('cmake --version')
    let l:version_str = matchstr(l:version_out, '\v\d+.\d+.\d+')
    let l:version_exp = split(l:version_str, '\.')
    let l:version = []
    for l:val in l:version_exp
         let l:version += [str2nr(l:val)]
    endfor
    return l:version
endfunction
```

**Comment by ilyachur** [comment]
Hi @WojciechMula,

I am ok with your solution, if it works for you.
Could you create a PR?
