### ISSUE TITLE
vimspector.json escaping backslashes

### ISSUE THREAD

**Issue by mark2185** [ilyachur/cmake4vim#81]
**Describe the bug**
In `.vimspector.json`, When I set `configuration[ 'args' ] = "--gtest_filter=TestSuite.\*"` (the same string I use when running from CLI, **with** the backslash), it replaces it with `"--gtest_filter=TestSuite.*"` after using `:CMakeRun`, and since I'm running `zsh` it fails (the `*` should be escaped in `zsh`.

**Expected behavior**
I would expect to use the same string for the `'args'` as I do in the commandline, just **one** backslash.

**Desktop:**
 - OS: macOS
 - Editor: vim
 - Version: 8.2, included patches: 1-2164

**Additional context**
The fix is to write a double backslash, e.g. `"--gtest_filter=TestSuite.\\*"` and then it expands it into `"--gtest_filter=TestSuite.\\\\*"` when writing into `.vimspector.json`.

Could the string not be escaped at all? Or just put a note in the `README.md` that the given string is not directly passed to the CLI.

EDIT: it looks like it's escaped every time, so after the second `:CMakeRun`, I get `TestSuite.\\\\\\\\*` which fails again.

**Comment by mark2185** [comment]
Eh, I tried fiddling with the `JSON` parsing in the code, I think I'll just resort to setting my shell to `/bin/bash` in `vim`.

**Comment by ilyachur** [comment]
@mark2185 Hmm, does  vimspector work as expected?
Need to investigate. Because I also use zsh and don't remember such issues. I will double check.

**Comment by mark2185** [comment]
For e.g. `--gtest_filter=TestSuite.*`, `CMakeRun` returns `no matches found: --gtest_filter=TestSuite.*`

Same thing for `TestSuite.\*`, but that's explained by `:help json_decode()`, `- Backslash in an invalid 2-character sequence escape is ignored, e.g. "\a" is decoded as "a"`.

And the field in `.vimspector.json` is changed to `TestSuite.*` (as expected by the documentation).

`TestSuite.\\*` works, but it gets written to `.vimspector.json` as `TestSuite.\\\\*`, because you decode it twice when parsing the file, once with `vim`, once with `python` (I'm guessing).

Then the next `CMakeRun` says `no matches found: --gtest_filter=TestSuite.\*` (which should actually be correct in `zsh`, huh, that's weird). But `.vimspector.json` contains `TestSuite.\\\\\\\\*` now.

Anyway, the number of backslashes keeps doubling.

`Vimspector` works as expected with `TestSuite.*`, crashes with `TestSuite.\*` because of invalid `\escape`, and doesn't work with `TestSuite.\\*`, it interprets it as `TestSuite.\*` (which again, **should** work in `zsh`)

**Comment by ilyachur** [comment]
@mark2185 Thank you for explanation. 
Yes it looks like a bug. 
And thank you that you found the bug and created this ticket.

**Comment by mark2185** [comment]
Somewhat related, why should **CMakeRun** _write_ to the `.vimspector.json`?

I'd expect **CMakeRun** to only read from the config (so I don't have to close it each time I change the config, I don't even have to do that for using `vimspector` alone), but **CMakeRun!** will write something to it.

**Comment by mark2185** [comment]
To answer my own question - I'm guessing it's to update the `program` field in `.vimspector.json`, i.e. the path to the binary.

**Comment by ilyachur** [comment]
> Somewhat related, why should **CMakeRun** _write_ to the `.vimspector.json`?

If you use `:CMakeRun` with any arguments, the command saves these arguments to `vimspector` config.

> I'd expect CMakeRun to only read from the config (so I don't have to close it each time I change the config, I don't even have to do that for using vimspector alone), but CMakeRun! will write something to it.

The idea was that `:CMakeRun` command allows to change vimspector config (it can changes the path to binary files and add arguments if you run own application with any arguments)

The `CMakeRun!` was introduced in order to reset previous arguments from `.vimspector.json`. Because in other case you don't have a chance to run command without arguments if `.vimspector.json` contains some arguments.

**Comment by ilyachur** [comment]
Try to fix this issue in the PR https://github.com/ilyachur/cmake4vim/pull/83

**Comment by ilyachur** [comment]
PR was merged to the master branch. @mark2185 Please confirm that problem is solved for your cases.

**Comment by mark2185** [comment]
@ilyachur works! Thanks!
