### ISSUE TITLE
Telescope integration with things like :CMakeSelectTarget

### ISSUE THREAD

**Issue by sam20908** [ilyachur/cmake4vim#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Native Telescope integration would be nice

**Describe alternatives you've considered**
I have considered using FZF, but since I'm using Telescope, and I don't really want FZF alongside Telescope.

**Additional context**

**Comment by ilyachur** [comment]
I am sure that Telescope supports extensions, but I cannot add it because I don't use Telescope.

**Comment by SantinoKeupp** [comment]
Since I was looking for the same thing, I decided to get my hands dirty. Hope that helps:

https://github.com/SantinoKeupp/telescope-cmake4vim.nvim

**Comment by ilyachur** [comment]
@sam20908 You can install extension with can add support of Telescope to this plugin.
@SantinoKeupp thank you for the implementation.

I updated the README and added information about extensions.
I will close this ticket. Feel free to reopen if you have any questions.
